--This query helps organize the data into a structured format and also extracts insights to answer business questions.

--Total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) AS revenue
FROM `customer-trends-analysis.customer.customer_trends`
GROUP BY gender;

--Customers applied discount but still spent more than the average purchase amount 
SELECT customer_id, purchase_amount 
FROM `customer-trends-analysis.customer.customer_trends` 
WHERE discount_applied = TRUE AND purchase_amount >= (SELECT AVG(purchase_amount) FROM `customer-trends-analysis.customer.customer_trends`);

--Top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) as average_product_rating
FROM `customer-trends-analysis.customer.customer_trends`
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Compare purchase amounts between Standard and Express Shipping. 
SELECT shipping_type, 
ROUND(AVG(purchase_amount),2) as average_purchase_amount
FROM `customer-trends-analysis.customer.customer_trends`
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS average_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM `customer-trends-analysis.customer.customer_trends`
GROUP BY subscription_status
ORDER BY total_revenue,average_spend DESC;

--Top 5 products have the highest discounts applied rate
SELECT item_purchased,
       ROUND((SUM(CASE WHEN discount_applied = TRUE THEN 1 ELSE 0 END)*100)/COUNT(*),2) AS discount_rate
FROM `customer-trends-analysis.customer.customer_trends`
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into New, Returning, and Loyal
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM `customer-trends-analysis.customer.customer_trends`)

SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type 
GROUP BY customer_segment;

--Top 3 most purchased products within each category 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
    FROM `customer-trends-analysis.customer.customer_trends`
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Repeat buyers (more than 5 previous purchases) vs. subscription status
SELECT subscription_status,
       COUNT(*) AS repeat_buyers
FROM `customer-trends-analysis.customer.customer_trends`
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Revenue contribution of each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM `customer-trends-analysis.customer.customer_trends`
GROUP BY age_group
ORDER BY total_revenue DESC;
